### ISSUE TITLE
How to use this tool for A2L merge?

### ISSUE THREAD

**Issue by DavidPYH** [DanielT/a2ltool#10]
Hello
I'm trying to use this tool to merge two different A2l file, but I don't have some knowledge for the command, when I input './a2ltool.exe --merge <Master.a2l>  --merge <Slavel.a2l> --output <new.a2l>', it give feedback on an error, whould you please help me to correct it？
Looking forward to your reply!

**Comment by DanielT** [comment]
Hello

The error message should have told you what you need to do. In this case the toll will print
```
error: the following required arguments were not provided:
  <INPUT|--create>

Usage: a2ltool.exe --merge <A2LFILE> <INPUT|--create>
```
This means you must specify one file as the base, or --create to create a new base.
The option --create mostly makes sense for other operations, when you're merging you just use one of your existing files
```
./a2ltool.exe <Master.a2l> --merge <Slavel.a2l> --output <new.a2l>
```
