### ISSUE TITLE
Is it possible to output a2l files as specific version?

### ISSUE THREAD

**Issue by xRowe** [DanielT/a2ltool#14]
Dear Developer

Does this awesome tool support to ouput a2l file as specifice version?
I used below command to create a2l file from elf, but it always output a2l file in ver1.71.
`a2ltool --create --elffile abc.elf --characteristic-regex .*?_Cal --measurement-regex .*?_Dis --output abc.a2l`

How can I output as another version?

Thanks,
Rowe

**Comment by DanielT** [comment]
Hi,
The feature to create files is rather simple, and many options cannot be set. This also includes the version.
However, you should not have any issues if you just use a text editor to modify the version in the created file.

Regards,
Daniel 

Am 8. Dezember 2023 13:31:12 MEZ schrieb xRowe ***@***.***>:

**Comment by DanielT** [comment]
Alternatively, you could create a mostly empty template file with any other tool you might be using.
That way you would be able to set the version, module name, memory segments, etc.
In this case you would then use a2ltool to add the measurements and characteristics.

**Comment by xRowe** [comment]
Thanks for your suggestion.
A2L generated from elf is good, and I could modify the version with notpad easily.

In fact, I have a a2l in version v1.71 created by Davinci, But in my hand, the version of a2l is too high to load with the current Tool(CANape), of course it is the problem that CANape version is a bit "old".
So I would tried to downgrade the version to somelike v1.4

Thank you
