### ISSUE TITLE
Is it possible to generate array parameter from elf file?

### ISSUE THREAD

**Issue by xRowe** [DanielT/a2ltool#23]
Hello Developer

Thanks again for the awesome tool, it help me a lot 

Is possible to generate an array parameter instead of separate into abc._1_ abc._2_ from elf file?

Cause there is a 300elements array Measurement parameter to load.

Thanks,
Rowe

**Comment by DanielT** [comment]
At the moment this is not possible.
I am currently working on support for complex types, such as structs (using TYPEDEF_STRUCTURE), and also arrays.

**Comment by xRowe** [comment]
Ahha, Great. 
Look forward to get this new feature.

Thank you

**Comment by DanielT** [comment]
I've just implemented this and it should work well enough.
Arrays can now be generated if the element type is a plain data type, like integer or boolean.
If your array contains structures, then you'll need to use a2l file version 1.7.1, and set --enable-structures, which enables the use of INSTANCES and TYPEDEF_STRUCTUREs.
