### ISSUE TITLE
Add "section" CLI option

### ISSUE THREAD

**Issue by plug-dricci** [DanielT/a2ltool#24]
Daniel,
Well done! this tool is excellent!  

I would like to request an "add measurement from section" command line option.  My diagnostic and/or calibration variables are often placed in their own sections (.diag and .cal in my case).  It would be very convenient to have the ability to create measurements and/or characteristics for all symbols in a particular section.

Keep up the good work!

**Comment by DanielT** [comment]
Thanks!

You should already be able to do that.
Most likely your sections sections are placed at fixed addresses - if they aren't you would have to find their addresses first.
Then you can use the --measurement-range and --characteristic-range options to add all symbols inside each range.

Example:
```
a2ltool input.a2l --elffile input.elf --measurement-range 0x1000 0x2000 --characteristic-range 0x2000 0x3000 --output out.a2l
```
