### ISSUE TITLE
converting a2l files to json

### ISSUE THREAD

**Issue by red-lac** [DanielT/a2ltool#33]
Dear developer, first of all, thank you for providing such a good a2l tool. This tool is great. Then, I have a request. Can this tool provide the function of converting a2l files to json or xml formats?

**Comment by DanielT** [comment]
Thanks!

At the moment a2ltool does not export to any other formats.
I also don't plan to add such a feature: It is not related to modifying and updating a2l files, and I think it is important to focus on the core use case.

You could
1) take a look at the output of `--debug-print`. This outputs the al2 data in rust debug format, which is similar, but not quite identical to JSON. However it also dumps the type info from the elf file if you have loaded one.
2) I separated the a2l file loading code into the `a2lfile` library. You could import it and build your own tool that outputs any format you need.

**Comment by red-lac** [comment]
alright, thank you very much
