### ISSUE TITLE
contact information

### ISSUE THREAD

**Issue by red-lac** [DanielT/a2ltool#35]
Hello, can you give me your contact information, skype or something? I have a requirement and would like to pay you to help me develop it.

**Comment by DanielT** [comment]
My email address is attached to every commit I make - but to be honest I'm not really interested in contract work.

**Comment by red-lac** [comment]
I sent you an email at daniel@dthaler.de. Is the email address correct? If you see the email, please reply.

**Comment by DanielT** [comment]
Yes, my address is correct. I get lots of mail, and none of it has "red-lac" as the sender.

I received replied to a message I thought might be from you a week ago, but maybe not? After all, you would not be asking here if you had received my reply.
