### ISSUE TITLE
How to Retrieve the Defined Values of Enums in if_data?

### ISSUE THREAD

**Issue by akikaede6** [DanielT/a2ltool#36]
Hello, I previously asked a question regarding `if_data` in the a2lfile repository([https://github.com/DanielT/a2lfile/issues/34](url)), and now I’m using the structures in the a2ltool repository to successfully retrieve the data I need from `if_data`. However, I’m having trouble retrieving the corresponding values of enums defined in the struct.

In the `fn generate_indirect_enum_parser(typename: &str, enumitems: &[EnumItem])` function in `a2lmacros/src/codegenerator/ifdata_parser.rs`, I understand that the values I need are stored in the `enitem.value`. But how can I access it in `decoded_ifdata.xcp`?

For example, in `OPTIONAL_CMD`, the value of `GET_ID` is defined as 250, but if I directly retrieve the enum as i32, the printed value is 1 instead of 250. How can I obtain the value defined in the enum?

Thank you very much for your help!

**Comment by DanielT** [comment]
Hello

Unfortunately there is currently no way to do this. It did not occur to me that anyone might want to do this, so these values are not made available when IF_DATA content is parsed.
As you noticed, the A2ML parser does have these values in its `EnumItem` struct, but code would have to be added to make them available later on.

**Comment by akikaede6** [comment]
I will try adding code to retrieve the values of the enums. Thanks for your help!

**Comment by DanielT** [comment]
Before you write new code - is there really a plausible reason to retrieve these values?

After thinking about your question for a while, it seems to me that there are really two scenarios:
1) You're working with your own ID_DATA block, or a standardized block. In this case you would already know any values associated with enums
2) You might read a third-party IF-DATA block, without support from the `a2ml_specification` macro. In this case you would not be able to use an enum value for anything, even if you had it

**Comment by akikaede6** [comment]
Here is my scenario: I am parsing a standard `if_data` block under a `module`, specifically the `xcp` and `xcpplus` modules as parsed in `a2ltools`. When parsing `OPTIONAL_CMD`, since it is an `enum`, when I want to get its command ID, I end up with a string or the position of the command in the enum, instead of the command ID I need. Therefore, I want to directly retrieve the value of this enum, rather than converting it again from its string, even though I already know the conversion relationship.

**Comment by DanielT** [comment]
I just pushed version 2.2.0 of a2lfile and a2lmacros.
This version allows you to get the values of enum items created by the a2ml_specification! macro
```
for opt_cmd in &protocol_layer.optional_cmd {
    println!("  Optional command: {:?} = {}", opt_cmd.xcp_options, opt_cmd.xcp_options as i32);
}
```
The key point here is `opt_cmd.xcp_options as i32`.

**Comment by akikaede6** [comment]
Thank you so much! This is exactly the functionality I was looking for. Your explanation was clear, and the implementation works perfectly for my needs. I appreciate your help!

**Comment by akikaede6** [comment]
By the way, I noticed that `tagged` data structures like `taggedstruct` are defined as `optional`, but I couldn't find a relevant definition in the `ASAM_AE_MCD-2_MC_BS` documentation. If a `taggedstruct` within the `IF_DATA` is not assigned a value, the parser considers it valid and can successfully parse it. However, for a regular `enum`, a value assignment is mandatory,  if not provided, the parser fails. Could you clarify which part of the standard this logic is based on?

**Comment by DanielT** [comment]
Can you give concrete details?
What definition are you using, and what IF_DATA block are you trying to parse with it?

**Comment by akikaede6** [comment]
I am using the example from `ASAP2 demo` for parsing, and in the `IF_DATA`  `XCP` section within the definition of `XCP_ON_CAN`’s `PROTOCOL_LAYER`, `byte_order` and `address_granularity` are not defined in block line 1416. When parsing this file, the absence of values for `byte_order` and `address_granularity`, which are mandatory fields, causes the parsing of this block to fail.
[ASAP2Example.zip](https://github.com/user-attachments/files/16885348/ASAP2Example.zip)
