### ISSUE TITLE
a2l merge:  function/group object name is incorrectly add .MERGE

### ISSUE THREAD

**Issue by qwertyuiopxu1** [DanielT/a2ltool#37]
for the GROUP/FUNCTION, the REF_CHARACTERISTIC/REF_MEASUREMENT may be incorrectly add the ".MERGE" suffix,  it is the same as
 the input_quantity of AXIS_DESCR, it should keep the raw name, so in INCA we can get the right refernce for the measurements or characteristics in the GROUP.

**Comment by qwertyuiopxu1** [comment]
Hi, this is a vary powerful tool for a2l merge and update address. thanks very much for sharing.
and I see you have made some fix on the merge operation for the input_quantity of AXIS_DESCR to make it can refer correctly in inca, but for GROUP/Function, it should do the same thing for REF_CHARACTERISTIC/REF_MEASUREMENT objects, here it also should use the raw name to make it can be add to experiment of inca.
![image](https://github.com/user-attachments/assets/d3108203-e4b8-4cb0-a98f-a72c7b3814d0)

**Comment by DanielT** [comment]
Hi,
Thanks for the report.
It sounds like the software is working as intended, unless I am misunderstanding you.

The intended behavior is that incoming objects that are in conflict with existing objects should be renamed with the suffix ".MERGE".
This prevents existing objects from being overwritten by new ones, and allows both to be used after merging.
References to the renamed objects should all also be updated. For example the REF_MEASUREMENT in a GROUP is updated during the merge.

Can you give a specific minimal example with input and output that demonstrates your problem?

**Comment by qwertyuiopxu1** [comment]
Hi,
Thank you for your reply.
For example, there are one measurement object with name Pw_TestLim in elf file, but with merge operation, there are will be Pw_TestLim and Pw_TestLim.MERGE for the measurements object, and there are two group refer this Pw_TestLim object and one is for define, another is for reference, but the merge operation will rename one to Pw_TestLim.MERGE1, so this is the wrong operation for group, the intened operation is keep the reference and defined object name as Pw_TestLim. this is similar as   input_quantity of AXIS_DESCR, keep the raw name.

**Comment by DanielT** [comment]
If the items on both sides of the merge are identical, then no copy with the suffix .MERGE is created.

When you have a measurement "Pw_TestLim" on both sides of the merge, but one side has different limits, or a different COMPU_METHOD, etc. then both of them will be retained by the merge.
The merge is designed to never lose any data, and there is no way to decide automatically which set of settings is "more correct".

In addition the merge must also be able to work without a loaded elf file, so the fact that both refer to the same variable in the elf file cannot be taken into account.

If you want to avoid the creation of .MERGE items, then you should either make sure each object only occurs on one side of the merge, or make sure all object data is identical.

**Comment by qwertyuiopxu1** [comment]
Hi,
maybe i didn't express clearly.
what I mean is when merge a2ls, the group is a stand alone unit, doesn't matter with the object.
it means the groups in differenct a2l file should be treated seperated.

**Comment by qwertyuiopxu1** [comment]
by the way,
there maybe one case when merge a2l: the first a2l file has multi-same name items due to some wrong operation. so do you think it is necessary to add one opiton to cleanup the duplicated object names. now i meet this situation there are 600+ same cases when i use the check operation. so please add one cleanupduplication operation for the first load a2l file.
![image](https://github.com/user-attachments/assets/d11756fb-a31f-496a-a938-0a48a3b7cc38)

**Comment by DanielT** [comment]
I have decided not to make any changes here. The line number information in the error messages should allow a person to fix the input files by hand.
That person can also judge which of the copies is the correct version, which a2ltool cannot do.
