### ISSUE TITLE
A new and more careless merge strategy needed

### ISSUE THREAD

**Issue by huibing** [DanielT/a2ltool#40]
hi @DanielT ,
could I suggest a new merge strategy when try to merge two a2ls? Please consider the following case where:
Suppose you have two a2ls, both a.a2l and b.a2l have a same group named group_1,
in a.a2l, you have 
```
/begin GROUP
      group_1
      "group_1 description: blah blah blah"
      /begin REF_CHARACTERISTIC
        cal1
        cal2
      /end REF_CHARACTERISTIC
      /begin REF_MEASUREMENT
        meas_1
        meas_2
      /end REF_MEASUREMENT
/end GROUP
```
in b.a2l, you have
```
/begin GROUP
      group_1
      "maybe different, but neither relevant nor important."
      /begin REF_CHARACTERISTIC
        cal1
        cal2
        cal3
      /end REF_CHARACTERISTIC
      /begin REF_MEASUREMENT
        meas_1
      /end REF_MEASUREMENT
/end GROUP
```
I think with a default merge operation, it is more safe to add a .MERGE to b.a2l group_1 in the merged.a2l. Nothing get lost in the merge process, and everything are kept as they were before the merge in case they are irrelevant items that happen to have the same name.

--------------------------------------------------------------------------------------------------------------------------------------------
However sometimes these two group_1 are the <mark>same</mark> one in different a2l files, so can I propose a new merge stategy where you treat these two groups as same group (in some cases, they are actually), and in the merged a2l you get:
```
/begin GROUP
      group_1
      "group_1 description: blah blah blah;maybe different, but neither relevant nor important."
      /begin REF_CHARACTERISTIC
        cal1
        cal2
        cal3
      /end REF_CHARACTERISTIC
      /begin REF_MEASUREMENT
        meas_1
        meas_2
      /end REF_MEASUREMENT
/end GROUP
```
This principle also applies to FUNCTION and TRANSFORMER.

**Comment by DanielT** [comment]
Hi, sorry for the late response - Life kept me busy and I haven't really had time to look at this.

My understanding is that you're proposing different behavior for GROUP, FUNCTION and TRANSFORMER.
For GROUP and FUNCTION I can see that that could make sense, maybe even as the default.

I haven't used TRANSFORMER much, but since this describes the transformation of data using an external dll, I don't think it should be merged. The transformer dll is a black box, and as far as I can tell there is no guarantee that it allows arbitrary inputs in the general case.

**Comment by huibing** [comment]
> Hi, sorry for the late response - Life kept me busy and I haven't really had time to look at this.
> 
> My understanding is that you're proposing different behavior for GROUP, FUNCTION and TRANSFORMER. For GROUP and FUNCTION I can see that that could make sense, maybe even as the default.
> 
> I haven't used TRANSFORMER much, but since this describes the transformation of data using an external dll, I don't think it should be merged. The transformer dll is a black box, and as far as I can tell there is no guarantee that it allows arbitrary inputs in the general case.

I don't encounter TRANSFORMER much in my work either, just my guess, so you're probably right about this.
I was thinking maybe a variety of merge strategies for user to select, e.g. --union-group --union-function --ours-measurement --theirs-characteristic --suffix-group=".MERGE" .
When a.a2l merge b.a2l, we found out one item name collision:
--suffix-group=".MERGE"   is current implementation, default case if no strategy is provided;
--ours-measurement     if this item is measurement use a.a2l's info;
--theirs-character          if this item is characteristic use b.a2l's info;
--union-group               as said before

Anyway, this is only a proposal, if this is too much trouble or not worth of the effort, I totally understand. Simply modify the behavior when merge GROUP and FUNCTION would be more than surfice for me.

**Comment by DanielT** [comment]
I have changed the behavior for GROUP and FUNCTION with the latest push to master.
It is part if the "update dependencies" commit, since the merge function is part of the a2lfile library.
