### ISSUE TITLE
a2l update: update of a struct returns struct address instead of element address

### ISSUE THREAD

**Issue by forstefa** [DanielT/a2ltool#42]
Hi, if I use the update function, I get the address of the structure instead of the address of the structure element for structure variables.

a2l sections:
a2l to update
```
        /begin CHARACTERISTIC
           Struct.Element1
            "Some text"
            VALUE
            0x0000
            UBYTE_COL_DIRECT
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct" 166
        /end CHARACTERISTIC

        /begin CHARACTERISTIC
           Struct.Element2
            "Some text"
            VALUE
            0x0000
            UBYTE_COL_DIRECT
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct" 168
        /end CHARACTERISTIC
``` 
updated A2L (same address for both characteristics)
```
        /begin CHARACTERISTIC
           Struct.Element1
            "Some text"
            VALUE
            0x80B08250
            UBYTE_COL_DIRECT
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct" 166
        /end CHARACTERISTIC

        /begin CHARACTERISTIC
           Struct.Element2
            "Some text"
            VALUE
            0x80B08250
            UBYTE_COL_DIRECT
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct" 168
        /end CHARACTERISTIC
``` 

If I edit the a2l to update: (UBYTE_CO_DIRECT -> UBYTE,  SYMBOL_LINK "Struct" 166 -> SYMBOL_LINK "Struct.Element1" 0)
```
        /begin CHARACTERISTIC
           Struct.Element1
            "Some text"
            VALUE
            0x0000
            UBYTE
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct.Element1" 0
        /end CHARACTERISTIC

        /begin CHARACTERISTIC
           Struct.Element2
            "Some text"
            VALUE
            0x0000
            UBYTE_COL_DIRECT
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct.Element2" 0
        /end CHARACTERISTIC
``` 

I get an updatet a2l with correct adresses
```
        /begin CHARACTERISTIC
           Struct.Element1
            "Some text"
            VALUE
           0x80B082F6
            UBYTE
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct.Element1" 0
        /end CHARACTERISTIC

        /begin CHARACTERISTIC
           Struct.Element2
            "Some text"
            VALUE
            0x80B082F8
            UBYTE_COL_DIRECT
            0
            NO_COMPU_METHOD
            0
            1
            BYTE_ORDER MSB_LAST
            SYMBOL_LINK "Struct.Element2" 0
        /end CHARACTERISTIC
``` 

Is that a bug?

**Comment by DanielT** [comment]
yes, that's a bug. I've never actually seen any file that has a non-zero offset on the SYMBOL_LINK, and the code isn't handling the value correctly

**Comment by forstefa** [comment]
Hi, I tried your bugfix and I think it´s not working proberly. In my a2l file there are many symbol_links with offset and I notice that every fourth entry (characteristic) is missing in the updated a2l file.

Example of the updatet a2l file:

characteristic_with_offset_01 
characteristic_with_offset_02
characteristic_with_offset_03
characteristic_with_offset_04 -> not in a2l file
characteristic_with_offset_05
characteristic_with_offset_06
characteristic_with_offset_07
characteristic_with_offset_08 -> not in a2l file
characteristic_with_offset_09
characteristic_with_offset_10
characteristic_with_offset_11
characteristic_with_offset_12 -> not in a2l file
characteristic_with_offset_13
characteristic_with_offset_14
characteristic_with_offset_15
characteristic_with_offset_16 -> not in a2l file
...

**Comment by DanielT** [comment]
This is probably not an error, depending on the definition of your data type
.
When an offset is used, a2ltool iterates over the content of complex data types, to find any atomic types at appropriate offsets.
Let's take a look at an example:
```C
struct example {
    uint8 value_a;
    uint8 value_b;
    /* 2 byte alignment gap */
    uint32 value_c;
};
struct example example_variable;
```
If we try to access this data using offsets, then:

    offset 0 = example_variable.value_a -> OK
    offset 1 = example_variable_value_b -> OK
    offset 2 = inside the alignment gap between values b and c -> rejected
    offset 3 = inside the alignment gap between values b and c -> rejected
    offset 4 = example_variable.value_c -> OK
    offset 5 = inside of example_variable.value_c, but value c does not start at this offset -> rejected
    offset 6 = inside of example_variable.value_c, but value c does not start at this offset -> rejected
    offset 7 = inside of example_variable.value_c, but value c does not start at this offset -> rejected
    offset 8 = outside of the referenced variable, example_variable, which is only 8 bytes long -> rejected
    offset -1 -> all negative offsets are always rejected

From your updated a2l I see that struct.characteristic_with_offset_00 and struct.characteristic_with_offset_04 have both been updated with a record layout called DefaultValueRecordLayout_uint32. This name indicates that these values are 32-bit values.
If the content of the record layout matches the name, then the rejected offsets are inside of the values, and are intentionally rejected.

**Comment by forstefa** [comment]
You are right, the base data type in the dwarf data is uint32 (--update mode was default).

When I try “update ADDRESSES”, I get nearly the same result, that only every fourth entry (characteristic) is included in the updated a2l file. Here the record layout remains uint8 (as intended with ADDRESSES). Is it possible to update also the addresses of the omitted characteristics in this mode?
With the SYMBOL_LINK with Offest it should be possible.

**Comment by DanielT** [comment]
I don't intend to implement that. Doing that would require a bit of reorganization in the code, while taking it in the wrong direction.
In my opinion rejecting bad offsets is a feature: it protects people against incorrectly calibrating their ECUs with bad a2l files.
If every offset is valid, then there is no longer a way to reject outdated (or otherwise bad) information in the a2l.
