### ISSUE TITLE
it doesn't work in my computer

### ISSUE THREAD

**Issue by DownyBehind** [DanielT/a2ltool#8]
Hello 

I am searching for an open-source tool for making A2L files and found it here. 
but this release file doesn't work on my computer. 

just the cmd window popped up and closed. 

my PC  information is below.

Processor : Intel(R) Xeno(R) Gold 6234 CPU@3.30GHz 
RAM : 32GB
OS : windows 10 Enterprise 64Bit

**Comment by DanielT** [comment]
a2ltool is a command line tool, so when you start it without any parameters it will only print a short message and then quit.
There is no graphical user interface.

You need to open a terminal (cmd or powershell or windows terminal), then you can go to the directory where you unpacked a2ltool and type ".\a2ltool --help"
This will show you the full help message, and then you can decide how to proceed from there.
