### ISSUE TITLE
ti arm compiler generated elfs have issues

### ISSUE THREAD

**Issue by Ahelion** [DanielT/a2ltool#9]
Hello Daniel,
I was playing arround with the Jacinto from TI, and I wanted to write some code for an ARM R5 core. At one point, I wanted to do some calibration using a2ls, I used the "--create" option and got this:
"
evaluate_exprloc eval result is unhandled: RequiresMemory {
    address: 536912364,
    size: 1,
    space: None,
    base_type: UnitOffset(
        0,
    ),
}
evaluate_exprloc eval result is unhandled: RequiresMemory {
    address: 0,
    size: 1,
    space: None,
    base_type: UnitOffset(
        0,
    ),
}"

The elf I used is the one from the TI demo website: https://software-dl.ti.com/codegen/docs/tiarmclang/compiler_tools_user_guide/getting_started_guide/building_simple_application.html
build using command line, not ccs.
Any idea what could be the issue?

**Comment by DanielT** [comment]
It looks like the TI compiler generated some complicated variable references. The DWARF debugging format is targeted at debuggers, and can express things like "use the value in memory (at runtime) to compute the location of this other value". That is what is being requested here.
A2ltool cannot do that, and the a2l format is not suited for variables whose location changes between runs anyway.
I'll take a longer look at this when I have more time, but I think the only thing that can be done is to delete the warning message.

**Comment by DanielT** [comment]
Commit 4db32d6 removes the warning message
